name: Create Unity Package

on: push

jobs:
  packaging:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo "Assets/Editor.meta" > packageList
        echo "Assets/Scripts.meta" >> packageList
        find Assets/Editor -name *.meta >> packageList
        find Assets/Scripts - name Meo*.meta >> packageList

    - run: mkdir output
    
    - uses: pCYSl5EDgo/create-unitypackage@master
      with:
        package-path: 'output/output.unitypackage'
        include-files: packageList
    - uses: actions/upload-artifact@master
      with:
        path: output
        name: package
